title: An Evolving Perspective
author: Mihir Vakharia
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Experiment ...
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: mihirv # DO NOT include the @ character, or else the build will fail!
github_username: mihirv # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
    skin: dark

minima:
  skin: dark
  social_links:
    twitter: mihirv
    linkedin: mihirvakharia
    pinterest: jekyll
    telegram: jekyll
    microdotblog: jekyll
    keybase: jekyll

plugins:
  # Adding RSS feed support
  - jekyll-feed
